### ISSUE TITLE
[Bug] WebServerBundle hardcoded to use web dir instead of public

### ISSUE THREAD

**Issue by JMLamodiere** [symfony/flex#125]
Since `web` directory has been moved to `public` in #122 , the command `make serve` results in an error **if** WebServerBundle is being used (ex : with `composer req webserver`) : 

    $ make serve
    [ERROR] The document root directory "/home/foo/demo/web" does not exist.

Web directory seems hardcoded in this bundle config : https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebServerBundle/Resources/config/webserver.xml#L17

**Comment by Pierstoval** [comment]
This has been fixed in the flex recipe:
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/Makefile#L16
You should update your makefile.

**Comment by JMLamodiere** [comment]
Indeed, it works with this fix. But I still get the old version of the Makefile when creating a new project from scratch with `composer create-project "symfony/skeleton:^3.3" demo` . Is there a cache somewhere ? I've tried to run `composer clear-cache` before, it did clear composer's cache, but it didn't fixed the problem of new projects having the old `Makefile`.

Thanks !

**Comment by fabpot** [comment]
Fixed now, cache was flushed on the server.

**Comment by Pierstoval** [comment]
@fabpot Can't cache be flushed anytime the recipes or recipes-contrib repo changes? A simple webhook should do the work, what do you think?

**Comment by fadykstas** [comment]
If your application's document root differs from the standard directory layout, you have to pass the correct location using the `--docroot` option:
` php bin/console server:start --docroot=public_html`
