### ISSUE TITLE
Unrecognized Bundle Classname

### ISSUE THREAD

**Issue by Spomky** [symfony/flex#227]
Hi,

When I install one of my bundles, the classname is not recognized and the bundle not installed.
You can reproduce it by executing the following command:

The complete framework:

```sh
composer require web-token/jwt-framework
```

or bundle only:

```sh
composer require web-token/jwt-bundle
```

It looks like the classname `Jose\Bundle\JoseFramework\JoseFrameworkBundle` is not detected and not added to the `bundle.php` file.

I cannot create a dedicated recipe ; it is rejected by the symfony bot as it contains only the bundle class.

**Comment by fabpot** [comment]
That's because the convention says that the namespace should end with `Bundle`, which is not the case here. It should be `Jose\Bundle\JoseFrameworkBundle\JoseFrameworkBundle`. I'm going to add this exception so that it is supported, but you should also fix it on your side if possible.

**Comment by fabpot** [comment]
fixed in #228

**Comment by Spomky** [comment]
Hi @fabpot,

I have just tested with your and quick fix or by changing the namespace as suggested and it works fine for the `web-token/jwt-bundle`.

The issue still exists when the whole framework is installed (i.e. `web-token/jwt-framework`).
I suppose this is a normal behaviour as flex tries to find the bundle classname using the namespace.

Anyway, thank you again for the quick reply. I will change the namespace ASAP.
