### ISSUE TITLE
Symfony Flex breaks interactivity of Composer scripts

### ISSUE THREAD

**Issue by apfelbox** [symfony/flex#285]
Hi,

I have a composer script defined:

```json
{
    "scripts": {
        "post-install-cmd": [
            "My\\Cool\\ScriptHandler::run"
        ],
        "post-update-cmd": [
            "My\\Cool\\ScriptHandler::run"
        ]
    }
}
```

which works, except for one difference: the given InputStream is non-interactive.

```php
<?php

use Composer\Script\Event;

class ScriptHandler
{
    public function handle (Event $event)
    {
        var_dump($event->getIO()->isInteractive());
    }
}
```

The problem is flex, as this short snipped shows:

```
$ composer run-script parameters
> My\Cool\ScriptHandler::handle
bool(false)


$ composer remove symfony/flex
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing symfony/flex (v1.0.60)
[...]


$ composer run-script parameters
> My\Cool\ScriptHandler::handle
bool(true)
```

This currently makes implementing something similar to `incenteev/composer-parameter-handler` in combination with running flex impossible.

**Comment by apfelbox** [comment]
As it turns out, interactivity is explicitly disabled:
https://github.com/symfony/flex/blob/558a09162d496a3b677bd1d0690470d59082c16c/src/Flex.php#L108

due to 

> removed question about removing VCS files

https://github.com/symfony/flex/commit/bce4c36ad8ebeb52f6296d7ab604296a395b259d

I will take a look, whether there is a better way to remove the question besides of completely disabling interactivity.

**Comment by apfelbox** [comment]
FYI: haven't found a way to disable the "remove vcd directory" message without disabling all interactivity in all dependency scripts.
Opened an issue at composer to discuss the possible solutions.

**Comment by ro0NL** [comment]
Quick reproducer on my side:

```
composer create-project symfony/skeleton app
cd app && composer req friendsofsymfony/elastica-bundle

Symfony operations: 1 recipe (87cd049614f216146bb961668dd54270)
  -  IGNORING  friendsofsymfony/elastica-bundle (>=5.0): From github.com/symfony/recipes-contrib:master
```

I can confirm `isInteractive` is false at this point.

**Comment by covex-nn** [comment]
May be it is not so important to `setInteractive(false)` ?

Or may be we could change [here](https://github.com/symfony/flex/blob/558a09162d496a3b677bd1d0690470d59082c16c/src/Flex.php#L101) default behavior of `create-project` command instead of `setInteractive(false)` ?

```php
            /** @var Application $app */
            $app = $trace['object'];
            /** @var \Composer\Command\CreateProjectCommand $command */
            $command = $app->find("create-project");
            $definition = $command->getDefinition();
            $definition->getOption('keep-vcs')->setDefault(false);
            $definition->getOption('prefer-dist')->setDefault(true);
            $definition->getOption('prefer-source')->setDefault(false);
```

^ i'm not sure if this will help

**Comment by covex-nn** [comment]
Also we could replace `create-project` command with a new one with overriden `installProject` method:

```php
<?php

namespace Symfony\Flex\Command;

use Composer\Config;
use Composer\Command\CreateProjectCommand as BaseCreateProjectCommand;
use Composer\IO\IOInterface;
use Symfony\Component\Console\Input\InputInterface;

class CreateProjectCommand extends BaseCreateProjectCommand
{
    public function installProject(IOInterface $io, Config $config, InputInterface $input, $packageName, $directory = null, $packageVersion = null, $stability = 'stable', $preferSource = false, $preferDist = false, $installDevPackages = false, $repository = null, $disablePlugins = false, $noScripts = false, $keepVcs = false, $noProgress = false, $noInstall = false, $ignorePlatformReqs = false, $secureHttp = true)
    {
        $interactive = $input->isInteractive();
        $input->setInteractive(false);
        parent::installProject($io, $config, $input, $packageName, $directory, $packageVersion, $stability, $preferSource, $preferDist, $installDevPackages, $repository, $disablePlugins, $noScripts, $keepVcs, $noProgress, $noInstall, $ignorePlatformReqs, $secureHttp);
        $input->setInteractive($interactive);
    }
}
```

And then create a command in `Symfony\Flex\Flex::activate`, like it happened with `require`, `remove` and `update` commands:

```php
$app->add(new Command\CreateProjectCommand());
```

I could create PR, but i do not understand why `$trace['args'][0]->setInteractive(false);` is in `Symfony\Flex\Flex::activate`. So, i can just suggest a changes =)

**Comment by apfelbox** [comment]
> May be it is not so important to `setInteractive(false)` ?

It is, as we don't want the message about removing the VCS.

> Or may be we could change here default behavior of `create-project` command instead of `setInteractive(false)`?

That would mean to duplicate the code from Composer. I would prefer to just keep using composer and fix this one issue. See the linked composer ticket for details.

**Comment by weaverryan** [comment]
This may have been resolved by #296. I believe the non-interactive was only meant to be done for create-project. That was accidentally changed, and #296 puts that back. This original report was about a script being run after a `composer remove`, and I believe that this will now be interactive again.

**Comment by apfelbox** [comment]
@weaverryan it is resolved for every instance except `create-project`. But the interactivity should work in every command, for example if you are using something like `incenteev/composer-parameter-handler` which tries to ask for config values when creating a project.

So we should really resolve it in every instance, which would be quite easy if the upstream composer ticket would get some traction.

**Comment by fabpot** [comment]
Note that if Composer were passing `$input` to the `installProject()` method instead of passing the result from `$input`, we would be able to change its value from Flex.

**Comment by apfelbox** [comment]
@seldaek would that work for you? ⬆️

**Comment by Seldaek** [comment]
@fabpot how would you do this? By extending installProject() and modifying before calling parent? If so why not extend execute() and do the same? Or did I miss something?

**Comment by Seldaek** [comment]
@fabpot https://github.com/composer/composer/commit/f42e6a5772c405efb6f2c46bec6fc0d1424acf61 should let you override the option's value at the time the flex plugin gets installed/enabled, if you know how to do that (I am still not sure, but I haven't checked in depth). Please report back here or at https://github.com/composer/composer/issues/7002 whether this helps.

**Comment by nicolas-grekas** [comment]
Should be fixed by #377.

**Comment by garak** [comment]
I just stumbled over this bug, with the latest flex (1.13.3) and the latest composer (2.1.3), so I guess it's not fixed yet.

Stack trace:

                                                                                                                                                 
>  [InvalidArgumentException]                                                                                                                      
  Invalid symfony/flex auto-script in composer.json: "Incenteev\ParameterHandler\ScriptHandler::buildParameters" is not a valid type of command.                                                                                                                                                  
Exception trace:
 () at /myproject/vendor/symfony/flex/src/ScriptExecutor.php:90
 Symfony\Flex\ScriptExecutor->expandCmd() at /myproject/vendor/symfony/flex/src/ScriptExecutor.php:48
 Symfony\Flex\ScriptExecutor->execute() at /myproject/vendor/symfony/flex/src/Flex.php:635
 Symfony\Flex\Flex->executeAutoScripts() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:190
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:102
 Composer\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:216
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:117
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:340
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:241
 Composer\Command\UpdateCommand->execute() at /myproject/vendor/symfony/flex/src/Command/UpdateCommand.php:39
 Symfony\Flex\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:312
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:125
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:64
 require() at /usr/local/bin/composer:24

**Comment by stof** [comment]
@garak please share the `scripts` section of your composer.json. I suspect that it is invalid, not respecting the format expected by Flex.

**Comment by garak** [comment]
```json
  "scripts": {
    "auto-scripts": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters"
    ],
    "post-install-cmd": [
      "@auto-scripts"
    ],
    "post-update-cmd": [
      "@auto-scripts"
    ]
  },
```

**Comment by stof** [comment]
Well, that's the issue. The Flex `auto-scripts` feature relies on a map, not on an object.
Here, it looks like you just want to use the composer feature of referencing another script while using the composer format for that script. Use a different name than `auto-scripts`

**Comment by stof** [comment]
side note: this has nothing to do with the original issue.
