### ISSUE TITLE
How to handle composer dev bundles in non-dev environments?

### ISSUE THREAD

**Issue by inverse** [symfony/flex#346]
I am trying to migrate an existing Symfony 4 application to flex and use the DoctrineMigrationBundle for both dev/test environments which is installed as a dev dependency. 

which all looks good in my bundles.php:

```
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
```

The problem comes when booting:

```
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".                  
  Did you forget a "use" statement for another namespace? in /var/www/kitaspot/releases/64/src/Kernel.php:33        
```

Since this is a dev dependency this is stripped out when deploying to production. What's advised in this situation? Aside including it as a normal dependency.

**Comment by xabbuh** [comment]
Are you accidentally running your application in the `dev` or `test` environment while not having installed the dev dependencies?

**Comment by inverse** [comment]
This error was observed when deploying with deployer. I'm pretty sure it's running in `prod`.

**Comment by inverse** [comment]
Any ideas. It's not just this bundle. I have

```
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
```

All of which are required as dev composer dependencies.

**Comment by inverse** [comment]
Could have been in `dev` as I didn't inject environemn

**Comment by inverse** [comment]
Resolved in: https://github.com/symfony/maker-bundle/issues/151

**Comment by Gemorroj** [comment]
but not resolved for me :/
```bash
export APP_ENV=prod
./composer.phar install --no-dev
```

```
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In AbstractRecursivePass.php line 122:
!!
!!    Invalid service "App\DataFixtures\AppFixtures": class "App\DataFixtures\App
!!    Fixtures" does not exist.
!!
!!
!!
Script @auto-scripts was called via post-install-cmd
```

bundles.php
```php
return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
];
```

composer.json
```json
{
    "type": "project",
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "ext-apcu": "*",
        "ext-gd": "*",
        "ext-pdo_sqlite": "*",
        "symfony/orm-pack": "*",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/monolog-bundle": "^3.2",
        "symfony/serializer-pack": "*",
        "symfony/yaml": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/validator": "^4.0",
        "nelmio/api-doc-bundle": "^3.2@dev",
        "imagine/imagine": "^0.7@dev"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.0",
        "symfony/var-dumper": "^4.0",
        "symfony/maker-bundle": "^1.4"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "01C0P3TPAW6JF5P0QRKQ1T7WZE",
            "allow-contrib": false
        }
    }
}
```

**Comment by weaverryan** [comment]
See symfony/symfony#27088

**Comment by Pierstoval** [comment]
Yes: update your  ̀config/bundles.php` and make sure the bundle is enabled only in tests & dev

**Comment by Pierstoval** [comment]
Heroku works with env vars, so you need to run `heroku config:set APP_ENV=prod` and run the same command for **every** env vars. Or you can use the `Settings` panel on your project's dashboard.

**Comment by jeroendesloovere** [comment]
Some more information:

## I believe cache:clear is not the problem
@weaverryan 
We can find `cache:clear` in `composer.json`. So heroku calls this over here...
```
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```
Local clearing of the cache gives no problems as you can see in the screenshots below.
![schermafbeelding 2018-07-06 om 11 35 05](https://user-images.githubusercontent.com/588616/42371754-afa6e8fe-8110-11e8-9790-acc4ea0fb271.png)
![schermafbeelding 2018-07-06 om 11 35 02](https://user-images.githubusercontent.com/588616/42371755-afc6b382-8110-11e8-96df-e8701f5c75fd.png)


## src/DataFixtures using DoctrineFixturesBundle classes

> Could this be the problem?

I have `src/DataFixtures/*` classes which use DoctrineFixturesBundle classes.
So I guess the problem has something to do with the following:
--> When running "production" environment, it tries to autowire all classes
```
# services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
```
=> But DoctrineFixturesBundle is not enabled for production environment in `config.bundles.php`:
`Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],`

### Possible solution?

Ignore autowiring on DataFixtures if in production environment?

**Comment by jeroendesloovere** [comment]
I have tried some things and found the solution.

Using `composer require doctrine-fixtures-bundle --dev` as described in the docs was so wrong.
It needs to be `composer require doctrine-fixtures-bundle`.

**Comment by rsavinkov** [comment]
@inverse, @Gemorroj, @jeroendesloovere 
Did you check `APP_ENV` on production evironment? Is it "prod"?
I had same problem, and I have just fixed it.

**Comment by ChoppyThing** [comment]
Still getting the same issue for this with deployer:

`  Script cache:clear returned with error code 255                                                                               
  !!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "MakerBundle" from namespace "Symfony\Bundle\MakerBundle".                                                                               
  !!  Did you forget a "use" statement for another namespace? in /home/homunity/site/homunity/releases/1/src/Kernel.php:43      
  !!  Stack trace:`

I can't figure out where cache:clear is getting the dev env from. In deployer the env is correctly set to prod. For now i've added debug and the web profiler to "normal" requirements(not dev) but it's weird to have this on a production environnement.

**Comment by inverse** [comment]
@ChoppyThing did you set the app env to production for deploy?

**Comment by ChoppyThing** [comment]
@inverse I did. I'll try this tomorrow, thanks.

**Comment by scasei** [comment]
The problem is `composer install --no-dev` install only bundles thats in `require`, but in config/bundles.php there is mostly a line like `Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class` but the class is never installed, and config/bundles.php is never updated.

**Comment by featuriz** [comment]
`APP_ENV=prod composer update --no-dev -o`
doc: https://symfony.com/doc/current/configuration.html#selecting-the-active-environment

**Comment by ctsDevel** [comment]
Same problem. bundles.php file is not updated when deploying to prod.

**Comment by featuriz** [comment]
> Same problem. bundles.php file is not updated when deploying to prod.

bundles.php file content will be like this,
```php
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
```
here `all` means, it will be loaded in all environments. 

If you have `flex bundle` it will automatically update this list, whenever you install or remove a bundle. If not then you have to do it manually.

If the module is missing here, then add it and set the environment accordingly. [Refer Symfony Doc for bundles](https://symfony.com/doc/current/bundles.html)

**Comment by vince83110** [comment]
Was it resolved ? I just upgraded to Symfony 7.4, and faced same error: 

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!   // Clearing the cache for the prod environment with debug false                
!!  
!!  13:51:05 CRITICAL  [php] Uncaught Error: Class "Doctrine\Bundle\FixturesBundle\Fixture" not found ["exception" => Error { …}]
!!  
!!  In CollaboratorImportFixtures.php line 16:
!!                                                                                 
!!    Attempted to load class "Fixture" from namespace "Doctrine\Bundle\FixturesB  
!!    undle".                                                                      
!!    Did you forget a "use" statement for another namespace?                      
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
```

Doc says nothing, I am blocked ..

**Comment by kozaki94** [comment]
I had the same problem. Symfony creates services in the container from classes in the `src/DataFixtures` folder. In config/services.yaml I had
```yaml
services:
    App\:
        resource: '../src/'
```
The solution was to add exclude
```yaml
services:
    App\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'
```
and create a config/packages/test/services.yaml file with
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\DataFixtures\:
        resource: '../../../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

```

**Comment by nicolas-grekas** [comment]
This deserves a separate bug report @kozaki94 
It happens only since 7.4.
Generally speaking, commenting on closed issues is the least effective way to get attention from maintainers.

**Comment by nicolas-grekas** [comment]
I created https://github.com/symfony/symfony/issues/62674
